"""
AI-Assisted Semantic Taxonomy Validation using Groq Free Tier.

Uses LLM-as-judge approach with structured prompting to classify
hallucination outputs into SP/PI/MF/CC categories. Compares against
heuristic classifier labels and identifies disagreements.

Zero additional cost: uses existing Groq API key (free tier).
"""
import json
import csv
import os
import time
import re
from pathlib import Path
from collections import Counter
from rdkit import Chem
from rdkit.Chem import Descriptors
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Taxonomy definitions for the LLM judge prompt
TAXONOMY_PROMPT = """You are a scientific taxonomy classifier for molecular hallucination analysis.

Given a molecule (SMILES notation) and a text description generated by an LLM, classify the description into EXACTLY ONE of these four categories:

## Categories

**SP (Structural Phantom)**: The text explicitly mentions chemical elements, functional groups, or structural features that are NOT present in the actual molecule. Example: claiming a molecule contains fluorine when the SMILES has no F atom, or mentioning a "pyridine ring" when no such ring exists.

**PI (Property Inversion)**: The text claims physicochemical properties that contradict the molecule's actual computed properties. Example: calling a highly lipophilic molecule (LogP > 3) "water soluble" or "hydrophilic", or calling a small polar molecule "highly lipophilic".

**MF (Mechanism Fabrication)**: The text names specific biological targets, receptors, enzymes, or cellular pathways (e.g., "EGFR inhibitor", "binds to p53", "COX-2 antagonist"). Generic mentions of "biological activity" do NOT count — only specific named targets.

**CC (Contextual Confabulation)**: The text is generically plausible but vague. It does not contain verifiable structural errors (SP), property contradictions (PI), or specific target claims (MF). This is the DEFAULT category for text that sounds scientific but makes no specific falsifiable claim.

## Classification Rules
1. Be CONSERVATIVE. Only classify as SP/PI/MF if you are confident. When in doubt, use CC.
2. SP requires the text to reference specific atoms/groups absent from the molecule.
3. PI requires a clear contradiction between claimed and actual properties.
4. MF requires naming a SPECIFIC biological target, not just generic "biological activity."
5. CC is the catch-all for vague, generic descriptions.

## Molecule Information
SMILES: {smiles}
Actual atoms present: {atoms}
Computed LogP: {logp:.2f}
Molecular weight: {mw:.1f}

## Text to classify
"{text}"

## Response Format
Respond with ONLY a JSON object (no markdown, no extra text):
{{"label": "XX", "confidence": 0.X, "reasoning": "brief explanation"}}

Where label is one of: SP, PI, MF, CC
And confidence is between 0.0 and 1.0
"""

def get_molecule_info(smiles):
    """Extract chemical properties for context."""
    mol = Chem.MolFromSmiles(smiles)
    if not mol:
        return {'atoms': 'INVALID', 'logp': 0.0, 'mw': 0.0}
    atoms = sorted(set(atom.GetSymbol() for atom in mol.GetAtoms()))
    logp = Descriptors.MolLogP(mol)
    mw = Descriptors.MolWt(mol)
    return {'atoms': ', '.join(atoms), 'logp': logp, 'mw': mw}

def classify_with_llm(client, smiles, text, model="llama-3.1-8b-instant"):
    """Send a single sample to the LLM judge."""
    info = get_molecule_info(smiles)
    
    prompt = TAXONOMY_PROMPT.format(
        smiles=smiles,
        atoms=info['atoms'],
        logp=info['logp'],
        mw=info['mw'],
        text=text
    )
    
    max_retries = 3
    delay = 3
    
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=200,
                temperature=0.0,
                seed=42,
            )
            content = response.choices[0].message.content.strip()
            
            # Parse JSON response
            # Handle cases where the model wraps in markdown code blocks
            if '```' in content:
                content = re.search(r'```(?:json)?\s*(.*?)\s*```', content, re.DOTALL)
                if content:
                    content = content.group(1)
                else:
                    content = response.choices[0].message.content.strip()
            
            result = json.loads(content)
            label = result.get('label', 'CC').upper()
            if label not in ('SP', 'PI', 'MF', 'CC'):
                label = 'CC'
            confidence = float(result.get('confidence', 0.5))
            reasoning = result.get('reasoning', '')
            
            return label, confidence, reasoning
            
        except json.JSONDecodeError:
            # Try to extract label from raw text
            content_upper = content.upper() if content else ''
            for lbl in ['SP', 'PI', 'MF', 'CC']:
                if lbl in content_upper:
                    return lbl, 0.3, f"Parsed from non-JSON response: {content[:100]}"
            return 'CC', 0.2, f"Failed to parse: {content[:100]}"
            
        except Exception as e:
            if 'rate_limit' in str(e).lower() and attempt < max_retries - 1:
                wait = delay * (attempt + 1)
                print(f"  Rate limit hit, waiting {wait}s...")
                time.sleep(wait)
            else:
                print(f"  Error: {e}")
                return 'CC', 0.0, f"API error: {str(e)[:80]}"
    
    return 'CC', 0.0, "Max retries exceeded"

def compute_agreement(heuristic_labels, ai_labels):
    """Compute agreement metrics between heuristic and AI labels."""
    from sklearn.metrics import cohen_kappa_score, confusion_matrix, classification_report
    
    # Overall agreement
    agree = sum(1 for h, a in zip(heuristic_labels, ai_labels) if h == a)
    total = len(heuristic_labels)
    
    print(f"\n{'='*60}")
    print(f"AGREEMENT ANALYSIS")
    print(f"{'='*60}")
    print(f"Raw agreement: {agree}/{total} ({agree/total*100:.1f}%)")
    
    # Cohen's Kappa
    kappa = cohen_kappa_score(heuristic_labels, ai_labels)
    print(f"Cohen's Kappa: {kappa:.3f}")
    
    if kappa < 0.2:
        interp = "Poor"
    elif kappa < 0.4:
        interp = "Fair"
    elif kappa < 0.6:
        interp = "Moderate"
    elif kappa < 0.8:
        interp = "Substantial"
    else:
        interp = "Almost Perfect"
    print(f"Interpretation: {interp}")
    
    # Confusion matrix
    labels_order = ['SP', 'PI', 'MF', 'CC']
    present_labels = sorted(set(heuristic_labels + ai_labels))
    
    cm = confusion_matrix(heuristic_labels, ai_labels, labels=labels_order)
    print(f"\nConfusion Matrix (rows=heuristic, cols=AI):")
    print(f"{'':>4} {'SP':>4} {'PI':>4} {'MF':>4} {'CC':>4}")
    for i, label in enumerate(labels_order):
        row = ' '.join(f'{v:>4}' for v in cm[i])
        print(f"{label:>4} {row}")
    
    # Per-category report
    print(f"\nPer-Category Classification Report:")
    report = classification_report(heuristic_labels, ai_labels, 
                                    labels=labels_order, zero_division=0)
    print(report)
    
    # Identify highest disagreement categories
    print(f"\nDisagreement Analysis:")
    disagree_from = Counter()
    disagree_to = Counter()
    for h, a in zip(heuristic_labels, ai_labels):
        if h != a:
            disagree_from[h] += 1
            disagree_to[a] += 1
            print(f"  Heuristic={h} → AI={a}")
    
    print(f"\nMost frequently reclassified FROM: {disagree_from.most_common(3)}")
    print(f"Most frequently reclassified TO:   {disagree_to.most_common(3)}")
    
    return kappa, cm

def main():
    # Load annotation sheet
    csv_path = Path('data/annotation/taxonomy_annotation_sheet.csv')
    if not csv_path.exists():
        print("Run generate_annotation_sheet.py first!")
        return
    
    # Read samples
    samples = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            samples.append(row)
    
    print(f"Loaded {len(samples)} samples for AI classification")
    
    # Initialize Groq client
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("ERROR: GROQ_API_KEY not found in environment")
        return
    
    client = Groq(api_key=api_key)
    
    # Classify each sample
    heuristic_labels = []
    ai_labels = []
    
    for i, sample in enumerate(samples):
        smiles = sample['smiles']
        text = sample['generated_text']
        heuristic = sample['heuristic_label']
        
        print(f"[{i+1}/{len(samples)}] Classifying... (heuristic={heuristic})", end=' ')
        
        ai_label, confidence, reasoning = classify_with_llm(client, smiles, text)
        
        # Determine if manual review is needed
        needs_review = (
            confidence < 0.6 or 
            ai_label != heuristic or
            'uncertain' in reasoning.lower()
        )
        
        samples[i]['ai_label'] = ai_label
        samples[i]['ai_confidence'] = f"{confidence:.2f}"
        samples[i]['ai_reasoning'] = reasoning
        samples[i]['manual_review_needed'] = 'YES' if needs_review else 'NO'
        
        heuristic_labels.append(heuristic)
        ai_labels.append(ai_label)
        
        status = "AGREE" if ai_label == heuristic else f"DISAGREE ({heuristic}->{ai_label})"
        print(f"-> {ai_label} (conf={confidence:.2f}) [{status}]")
        
        # Small delay to respect rate limits
        time.sleep(0.5)
    
    # Save updated CSV
    out_path = Path('data/annotation/taxonomy_validated.csv')
    fieldnames = [
        'sample_id', 'dataset', 'index', 'smiles', 'condition',
        'generated_text', 'heuristic_label',
        'ai_label', 'ai_confidence', 'ai_reasoning',
        'manual_review_needed', 'manual_label'
    ]
    
    with open(out_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for s in samples:
            writer.writerow(s)
    
    print(f"\nSaved validated annotations to: {out_path}")
    
    # Compute agreement
    kappa, cm = compute_agreement(heuristic_labels, ai_labels)
    
    # Summary statistics
    n_review = sum(1 for s in samples if s['manual_review_needed'] == 'YES')
    print(f"\nSamples needing manual review: {n_review}/{len(samples)} ({n_review/len(samples)*100:.0f}%)")
    
    # Save summary report
    report_path = Path('data/annotation/validation_report.json')
    report = {
        'total_samples': len(samples),
        'cohens_kappa': round(kappa, 3),
        'raw_agreement': round(sum(1 for h, a in zip(heuristic_labels, ai_labels) if h == a) / len(samples), 3),
        'manual_review_needed': n_review,
        'heuristic_distribution': dict(Counter(heuristic_labels)),
        'ai_distribution': dict(Counter(ai_labels)),
        'confusion_matrix': cm.tolist(),
    }
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=2)
    
    print(f"Saved validation report to: {report_path}")

if __name__ == '__main__':
    main()
